#!/bin/sh

#rm -rf configure
rm -rf autom4te.cache/ 
rm -f config.log config.status 

rm -f src/*.o src/*.so src/*.dylib 

rm -f *.zip

rm -rf inst/include
rm -rf inst/share
rm -rf inst/lib
rm -rf inst/bin

rm -rf windows/

cd src/geos
#if test -e "Makefile"; then
#  make clean
#fi

rm -f Makefile
