#!/bin/sh

R_HOME=`R RHOME`
if test -z "${R_HOME}"; then
  echo "Could not determine R_HOME."
  exit 1
fi

prefix=`${R_HOME}/bin/Rscript -e "cat(libgeos::geos_prefix())"`
exec_prefix=${prefix}
libdir=${exec_prefix}/lib

usage()
{
  cat <<EOF
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--clibs]
     [--cclibs]
     [--static-clibs]
     [--static-cclibs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
EOF
  exit $1
}

if test $# -eq 0; then
  usage 1 1>&2
fi

while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac
  case $1 in
    --prefix)
      echo ${prefix}
      ;;
    --version)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_version())"`
      ;;
    --cflags)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_cflags())"`
      ;;
    --libs)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_libs())"`
      ;;
    --clibs)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_clibs())"`
      ;;
    --cclibs)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_cclibs())"`
      ;;
    --static-clibs)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_static_clibs())"`
      ;;
    --static-cclibs)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_static_cclibs())"`
      ;;
    --ldflags)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_ldflags())"`
      ;;
    --includes)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_includes())"`
      ;;
    --jtsport)
      echo `${R_HOME}/bin/Rscript -e "cat(libgeos::geos_jtsport())"`
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

