#!/bin/sh

rm -rf src/geos-*.*.*
rm -rf src/geos

GEOS_VERSION=`grep "Version:" DESCRIPTION | cut -d" " -f2 | cut -d"-" -f1`

GEOS_URL="http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2"
GEOS_DIR="src/geos"


R_HOME=`R RHOME`
if test -z "${R_HOME}"; then
  echo "Could not determine R_HOME."
  exit 1
fi


echo "Downloading geos v${GEOS_VERSION} from ${GEOS_URL}."
${R_HOME}/bin/Rscript tools/download_zip.R "${GEOS_URL}" "src/"

mv src/geos-*.*.* src/geos

cd src/geos
 
aclocal
automake
autoconf
