// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// geos_version
Rcpp::IntegerVector geos_version(bool c_api);
RcppExport SEXP libgeos_geos_version(SEXP c_apiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type c_api(c_apiSEXP);
    rcpp_result_gen = Rcpp::wrap(geos_version(c_api));
    return rcpp_result_gen;
END_RCPP
}
// test_api
int test_api(std::string wkt);
RcppExport SEXP libgeos_test_api(SEXP wktSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type wkt(wktSEXP);
    rcpp_result_gen = Rcpp::wrap(test_api(wkt));
    return rcpp_result_gen;
END_RCPP
}
