# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get geos C API version
#'
#' @export
geos_c_api_version <- function() {
    .Call(`_libgeos_geos_c_api_version`)
}

#' Get geos library version
#'
#' @export
geos_version <- function() {
    .Call(`_libgeos_geos_version`)
}

#' Get geos jts port version
#'
#' @export
geos_jtsport <- function() {
    .Call(`_libgeos_geos_jtsport`)
}

