# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geos_version <- function(c_api = FALSE) {
    .Call('libgeos_geos_version', PACKAGE = 'libgeos', c_api)
}

test_api <- function(wkt) {
    .Call('libgeos_test_api', PACKAGE = 'libgeos', wkt)
}

