# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geos_c_api_version <- function() {
    .Call('_libgeos_geos_c_api_version', PACKAGE = 'libgeos')
}

geos_version <- function() {
    .Call('_libgeos_geos_version', PACKAGE = 'libgeos')
}

geos_jtsport <- function() {
    .Call('_libgeos_geos_jtsport', PACKAGE = 'libgeos')
}

